### ISSUE TITLE
how to use SingleDiscCond?

### ISSUE THREAD

**Issue by 980202006** [autonomousvision/projected_gan#18]
I noticed that there is a SingleDiscCond class in your code. Can this be used as a discriminator for classification and how to add loss to it

**Comment by xl-sr** [comment]
It is a class-conditional discriminator and is used if you train on eg.cCIFAR 10 and pass ```--cond=True``` as an argument.

More info here: https://paperswithcode.com/method/projection-discriminator

**Comment by gigadeplex** [comment]
@xl-sr  what if you don't have a conditional label? I'm trying to replace my discriminator, d(x), in my project but the projected discriminator always takes in a conditional label d(x, y).

**Comment by woctezuma** [comment]
If you don't have a label to condition with, then why not use the following one?

https://github.com/autonomousvision/projected_gan/blob/10ae1313823847a6d1780339c808d2cb7efbf560/pg_modules/discriminator.py#L12

Instead of the conditional one?

https://github.com/autonomousvision/projected_gan/blob/10ae1313823847a6d1780339c808d2cb7efbf560/pg_modules/discriminator.py#L55
