### ISSUE TITLE
Confused about the image blur strategy used in the discriminator

### ISSUE THREAD

**Issue by neuralchen** [autonomousvision/projected_gan#42]
This is a very nice paper!
I have some naive questions:
1. what is the purpose of image blur and does it have to be added? If it is optional, how much does it affect the result?
2. what is the function of "self.interp224"? Different resolutions (e.g. 512) need to be interpolated to 224？

Looking forward to your reply！

**Comment by woctezuma** [comment]
Regarding question n°2, it is boolean value, set to True for small images:

https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/train.py#L240

**Comment by xl-sr** [comment]
regarding question 1, this is introduced by StyleGAN3 from which we are using large parts of their codebase. It is used to train StyleGAN3-R, since it is slow to learn high frequencies, which is eased by blurring. In the current state of the code base it is not used, but I left it for forward compatibility ;)
