### ISSUE TITLE
How to reproduce the numbers in paper

### ISSUE THREAD

**Issue by limbo0000** [autonomousvision/projected_gan#50]
Thanks for your nice work!

After running the official implementation of FFHQ256-full (using cfg stylegan2, 64 batch size in total, 10000 kimg, efficientnet lite0),  the best FID is only 6.2, far away from the original StyleGAN2 and your paper. Is there something important that I missed?

Looking forward to your reply.

**Comment by xl-sr** [comment]
Hey :) 

the StyleGAN2+PG combo is sth we didn't investigate deeply, so the values from the paper are for FastGAN+PG.

 I also changed I few things for the release because I did not like the quality of the FFHQ samples, even though the FID was low (see limitations section). I added for example a hypersphere mapping of the input
https://github.com/autonomousvision/projected_gan/blob/81f4af0b776c9f1612b7b355601e032b99a60f77/pg_modules/networks_fastgan.py#L60

When I run the current code, I get down to an FID of 3.89 which is slightly higher than what we had in the paper, but the samples are much better. So I recommend you try ```--cfg=fastgan``` or you need to search for a good learning rate for StyleGAN2+PG.

**Comment by limbo0000** [comment]
Hi Axel @xl-sr,

Thanks for your help. I will try fastgan soon.
