### ISSUE TITLE
Weights for LSUN Bedrooms?

### ISSUE THREAD

**Issue by dave-epstein** [autonomousvision/projected_gan#62]
Hi - wondering if by any chance you can release weights for your model trained on LSUN Bedrooms.

Thanks!

**Comment by xl-sr** [comment]
Hi Dave, 

they'll be up by tomorrow. :)

I retrained with the refactored codebase, the model reaches an FID of 2.1. This value is slightly higher than reported in the paper which is likely due to additional constraints I added (hypersphere mapping, etc). The results look better visually, if you want to reach the original numbers, I recommend training without these constraints.
